// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: raiting/v1/raiting.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaitingService_GetStudentJournal_FullMethodName   = "/school_online.raiting.v1.RaitingService/GetStudentJournal"
	RaitingService_GetClassroomJournal_FullMethodName = "/school_online.raiting.v1.RaitingService/GetClassroomJournal"
	RaitingService_UpdateGrade_FullMethodName         = "/school_online.raiting.v1.RaitingService/UpdateGrade"
)

// RaitingServiceClient is the client API for RaitingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaitingServiceClient interface {
	GetStudentJournal(ctx context.Context, in *GetJournalRequest, opts ...grpc.CallOption) (*GetStudentJournalResponse, error)
	GetClassroomJournal(ctx context.Context, in *GetJournalRequest, opts ...grpc.CallOption) (*GetClassroomJournalResponse, error)
	UpdateGrade(ctx context.Context, in *UpdateJournalRequest, opts ...grpc.CallOption) (*UpdateJournalResponse, error)
}

type raitingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaitingServiceClient(cc grpc.ClientConnInterface) RaitingServiceClient {
	return &raitingServiceClient{cc}
}

func (c *raitingServiceClient) GetStudentJournal(ctx context.Context, in *GetJournalRequest, opts ...grpc.CallOption) (*GetStudentJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentJournalResponse)
	err := c.cc.Invoke(ctx, RaitingService_GetStudentJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raitingServiceClient) GetClassroomJournal(ctx context.Context, in *GetJournalRequest, opts ...grpc.CallOption) (*GetClassroomJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClassroomJournalResponse)
	err := c.cc.Invoke(ctx, RaitingService_GetClassroomJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raitingServiceClient) UpdateGrade(ctx context.Context, in *UpdateJournalRequest, opts ...grpc.CallOption) (*UpdateJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJournalResponse)
	err := c.cc.Invoke(ctx, RaitingService_UpdateGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaitingServiceServer is the server API for RaitingService service.
// All implementations must embed UnimplementedRaitingServiceServer
// for forward compatibility.
type RaitingServiceServer interface {
	GetStudentJournal(context.Context, *GetJournalRequest) (*GetStudentJournalResponse, error)
	GetClassroomJournal(context.Context, *GetJournalRequest) (*GetClassroomJournalResponse, error)
	UpdateGrade(context.Context, *UpdateJournalRequest) (*UpdateJournalResponse, error)
	mustEmbedUnimplementedRaitingServiceServer()
}

// UnimplementedRaitingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaitingServiceServer struct{}

func (UnimplementedRaitingServiceServer) GetStudentJournal(context.Context, *GetJournalRequest) (*GetStudentJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStudentJournal not implemented")
}
func (UnimplementedRaitingServiceServer) GetClassroomJournal(context.Context, *GetJournalRequest) (*GetClassroomJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClassroomJournal not implemented")
}
func (UnimplementedRaitingServiceServer) UpdateGrade(context.Context, *UpdateJournalRequest) (*UpdateJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGrade not implemented")
}
func (UnimplementedRaitingServiceServer) mustEmbedUnimplementedRaitingServiceServer() {}
func (UnimplementedRaitingServiceServer) testEmbeddedByValue()                        {}

// UnsafeRaitingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaitingServiceServer will
// result in compilation errors.
type UnsafeRaitingServiceServer interface {
	mustEmbedUnimplementedRaitingServiceServer()
}

func RegisterRaitingServiceServer(s grpc.ServiceRegistrar, srv RaitingServiceServer) {
	// If the following call panics, it indicates UnimplementedRaitingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaitingService_ServiceDesc, srv)
}

func _RaitingService_GetStudentJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaitingServiceServer).GetStudentJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaitingService_GetStudentJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaitingServiceServer).GetStudentJournal(ctx, req.(*GetJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaitingService_GetClassroomJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaitingServiceServer).GetClassroomJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaitingService_GetClassroomJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaitingServiceServer).GetClassroomJournal(ctx, req.(*GetJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaitingService_UpdateGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaitingServiceServer).UpdateGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaitingService_UpdateGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaitingServiceServer).UpdateGrade(ctx, req.(*UpdateJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaitingService_ServiceDesc is the grpc.ServiceDesc for RaitingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaitingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "school_online.raiting.v1.RaitingService",
	HandlerType: (*RaitingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentJournal",
			Handler:    _RaitingService_GetStudentJournal_Handler,
		},
		{
			MethodName: "GetClassroomJournal",
			Handler:    _RaitingService_GetClassroomJournal_Handler,
		},
		{
			MethodName: "UpdateGrade",
			Handler:    _RaitingService_UpdateGrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raiting/v1/raiting.proto",
}
