syntax = "proto3";


package school_online.user.v1;

option go_package = "github.com/abozorov/school_online/grpc_api/user;v1";

service UserService {
        rpc Get(GetUserRequest) returns (GetUserResponse);
        rpc GetByEmail(GetByEmailRequest) returns (GetUserResponse);
        rpc GetAll(GetAllRequest) returns (GetAllUsersResponse);
        rpc Create(CreateUserRequest) returns (CreateUserResponse);
        rpc Update(UpdateUserRequest) returns (UpdateUserResponse);
        rpc Delete(DeleteUserRequest) returns (DeleteUserResponse);
        rpc CreateSubject(CreateSubjectRequest) returns (CreateSubjectResponse);
        rpc GetSubjectById(GetSubjectByIdRequest) returns (GetSubjectByIdResponse);
        rpc GetAllSubjects(GetAllRequest) returns (GetAllSubjectsResponse);
        rpc UpdateSubject(UpdateSubjectRequest) returns (UpdateSubjectResponse);
}

message GetAllSubjectsResponse {
        repeated GetSubjectByIdResponse subjects = 1;
}

message GetSubjectByIdRequest {
        int32 id = 1;
}

message GetSubjectByIdResponse {
        int32 id = 1;
        string name = 2;
        string description = 3;
}

message GetByEmailRequest {
        string email = 1;
}

message UpdateSubjectRequest {
        int32 id = 1;
        optional string name = 2;
        optional string description = 3;
}

message UpdateSubjectResponse {
}

message CreateSubjectRequest {
        string name = 1;
        string description = 2;
}

message CreateSubjectResponse {
        int32 id = 1;
}

message DeleteUserRequest {
        int32 id = 1;
}

message DeleteUserResponse {
}

message UpdateUserRequest {
        int32 id = 1;
        optional string name = 2;
        optional string username = 3;
        optional string phone_number = 4;
        optional string role = 5;
        optional string birthday = 6;
        optional Student student = 7;
        optional Parent parent = 8;
        optional Stuff stuff = 9;
        optional Teacher teacher = 10;
}

message UpdateUserResponse {
}

message CreateUserRequest {
        string name = 1;
        string username = 2;
        string email = 3;
        string password = 4;
        optional string phone_number = 5;
        string role = 6;
        optional string birthday = 7;
        optional Student student = 8;
        optional Parent parent = 9;
        optional Stuff stuff = 10;
        optional Teacher teacher = 11;
}

message CreateUserResponse {
        int32 id = 1;
}

message GetAllRequest {
}

message GetAllUsersResponse {
        repeated GetUserResponse users = 1;
}

message GetUserRequest {
        int32 id = 1;
}

message GetUserResponse {
        int32 id = 1;
        string name = 2;
        string username = 3;
        string email = 4;
        bool verify_email = 5;
        string password = 6;
        string phone_number = 7;
        string role = 8;
        string birthday = 9;
        Student student = 10;
        Parent parent = 11;
        Stuff stuff = 12;
        Teacher teacher = 13;
}
message Student {
        int32 class_id = 1;
}

message Parent {
        repeated int32 students_id = 1;
}

message Stuff {
        string position = 1;
        int32 experience = 2;
}

message Teacher {
        repeated int32 subjects_id = 1;
        int32 experience = 2;
}
