// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: classroom/v1/classroom.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClassroomService_GetClassroom_FullMethodName           = "/school_online.classroom.v1.ClassroomService/GetClassroom"
	ClassroomService_ListClassrooms_FullMethodName         = "/school_online.classroom.v1.ClassroomService/ListClassrooms"
	ClassroomService_CreateClassroom_FullMethodName        = "/school_online.classroom.v1.ClassroomService/CreateClassroom"
	ClassroomService_UpdateClassroom_FullMethodName        = "/school_online.classroom.v1.ClassroomService/UpdateClassroom"
	ClassroomService_DeleteClassroom_FullMethodName        = "/school_online.classroom.v1.ClassroomService/DeleteClassroom"
	ClassroomService_GetScheduleByClassroom_FullMethodName = "/school_online.classroom.v1.ClassroomService/GetScheduleByClassroom"
	ClassroomService_GetScheduleByTeacher_FullMethodName   = "/school_online.classroom.v1.ClassroomService/GetScheduleByTeacher"
	ClassroomService_CreateSchedule_FullMethodName         = "/school_online.classroom.v1.ClassroomService/CreateSchedule"
	ClassroomService_UpdateSchedule_FullMethodName         = "/school_online.classroom.v1.ClassroomService/UpdateSchedule"
	ClassroomService_DeleteSchedule_FullMethodName         = "/school_online.classroom.v1.ClassroomService/DeleteSchedule"
)

// ClassroomServiceClient is the client API for ClassroomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClassroomServiceClient interface {
	GetClassroom(ctx context.Context, in *GetClassroomRequest, opts ...grpc.CallOption) (*ClassroomResponse, error)
	ListClassrooms(ctx context.Context, in *ListClassroomsRequest, opts ...grpc.CallOption) (*ListClassroomsResponse, error)
	CreateClassroom(ctx context.Context, in *CreateClassroomRequest, opts ...grpc.CallOption) (*CreateClassroomResponse, error)
	UpdateClassroom(ctx context.Context, in *UpdateClassroomRequest, opts ...grpc.CallOption) (*UpdateClassroomResponse, error)
	DeleteClassroom(ctx context.Context, in *DeleteClassroomRequest, opts ...grpc.CallOption) (*DeleteClassroomResponse, error)
	GetScheduleByClassroom(ctx context.Context, in *GetScheduleByClassroomRequest, opts ...grpc.CallOption) (*ScheduleList, error)
	GetScheduleByTeacher(ctx context.Context, in *GetScheduleByTeacherRequest, opts ...grpc.CallOption) (*ScheduleList, error)
	CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*CreateScheduleResponse, error)
	UpdateSchedule(ctx context.Context, in *UpdateScheduleRequest, opts ...grpc.CallOption) (*UpdateScheduleResponse, error)
	DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error)
}

type classroomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClassroomServiceClient(cc grpc.ClientConnInterface) ClassroomServiceClient {
	return &classroomServiceClient{cc}
}

func (c *classroomServiceClient) GetClassroom(ctx context.Context, in *GetClassroomRequest, opts ...grpc.CallOption) (*ClassroomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassroomResponse)
	err := c.cc.Invoke(ctx, ClassroomService_GetClassroom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) ListClassrooms(ctx context.Context, in *ListClassroomsRequest, opts ...grpc.CallOption) (*ListClassroomsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClassroomsResponse)
	err := c.cc.Invoke(ctx, ClassroomService_ListClassrooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) CreateClassroom(ctx context.Context, in *CreateClassroomRequest, opts ...grpc.CallOption) (*CreateClassroomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClassroomResponse)
	err := c.cc.Invoke(ctx, ClassroomService_CreateClassroom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) UpdateClassroom(ctx context.Context, in *UpdateClassroomRequest, opts ...grpc.CallOption) (*UpdateClassroomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateClassroomResponse)
	err := c.cc.Invoke(ctx, ClassroomService_UpdateClassroom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) DeleteClassroom(ctx context.Context, in *DeleteClassroomRequest, opts ...grpc.CallOption) (*DeleteClassroomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteClassroomResponse)
	err := c.cc.Invoke(ctx, ClassroomService_DeleteClassroom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) GetScheduleByClassroom(ctx context.Context, in *GetScheduleByClassroomRequest, opts ...grpc.CallOption) (*ScheduleList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleList)
	err := c.cc.Invoke(ctx, ClassroomService_GetScheduleByClassroom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) GetScheduleByTeacher(ctx context.Context, in *GetScheduleByTeacherRequest, opts ...grpc.CallOption) (*ScheduleList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleList)
	err := c.cc.Invoke(ctx, ClassroomService_GetScheduleByTeacher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*CreateScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateScheduleResponse)
	err := c.cc.Invoke(ctx, ClassroomService_CreateSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) UpdateSchedule(ctx context.Context, in *UpdateScheduleRequest, opts ...grpc.CallOption) (*UpdateScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateScheduleResponse)
	err := c.cc.Invoke(ctx, ClassroomService_UpdateSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteScheduleResponse)
	err := c.cc.Invoke(ctx, ClassroomService_DeleteSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassroomServiceServer is the server API for ClassroomService service.
// All implementations must embed UnimplementedClassroomServiceServer
// for forward compatibility.
type ClassroomServiceServer interface {
	GetClassroom(context.Context, *GetClassroomRequest) (*ClassroomResponse, error)
	ListClassrooms(context.Context, *ListClassroomsRequest) (*ListClassroomsResponse, error)
	CreateClassroom(context.Context, *CreateClassroomRequest) (*CreateClassroomResponse, error)
	UpdateClassroom(context.Context, *UpdateClassroomRequest) (*UpdateClassroomResponse, error)
	DeleteClassroom(context.Context, *DeleteClassroomRequest) (*DeleteClassroomResponse, error)
	GetScheduleByClassroom(context.Context, *GetScheduleByClassroomRequest) (*ScheduleList, error)
	GetScheduleByTeacher(context.Context, *GetScheduleByTeacherRequest) (*ScheduleList, error)
	CreateSchedule(context.Context, *CreateScheduleRequest) (*CreateScheduleResponse, error)
	UpdateSchedule(context.Context, *UpdateScheduleRequest) (*UpdateScheduleResponse, error)
	DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteScheduleResponse, error)
	mustEmbedUnimplementedClassroomServiceServer()
}

// UnimplementedClassroomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClassroomServiceServer struct{}

func (UnimplementedClassroomServiceServer) GetClassroom(context.Context, *GetClassroomRequest) (*ClassroomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClassroom not implemented")
}
func (UnimplementedClassroomServiceServer) ListClassrooms(context.Context, *ListClassroomsRequest) (*ListClassroomsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClassrooms not implemented")
}
func (UnimplementedClassroomServiceServer) CreateClassroom(context.Context, *CreateClassroomRequest) (*CreateClassroomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClassroom not implemented")
}
func (UnimplementedClassroomServiceServer) UpdateClassroom(context.Context, *UpdateClassroomRequest) (*UpdateClassroomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateClassroom not implemented")
}
func (UnimplementedClassroomServiceServer) DeleteClassroom(context.Context, *DeleteClassroomRequest) (*DeleteClassroomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteClassroom not implemented")
}
func (UnimplementedClassroomServiceServer) GetScheduleByClassroom(context.Context, *GetScheduleByClassroomRequest) (*ScheduleList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScheduleByClassroom not implemented")
}
func (UnimplementedClassroomServiceServer) GetScheduleByTeacher(context.Context, *GetScheduleByTeacherRequest) (*ScheduleList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScheduleByTeacher not implemented")
}
func (UnimplementedClassroomServiceServer) CreateSchedule(context.Context, *CreateScheduleRequest) (*CreateScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSchedule not implemented")
}
func (UnimplementedClassroomServiceServer) UpdateSchedule(context.Context, *UpdateScheduleRequest) (*UpdateScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSchedule not implemented")
}
func (UnimplementedClassroomServiceServer) DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSchedule not implemented")
}
func (UnimplementedClassroomServiceServer) mustEmbedUnimplementedClassroomServiceServer() {}
func (UnimplementedClassroomServiceServer) testEmbeddedByValue()                          {}

// UnsafeClassroomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassroomServiceServer will
// result in compilation errors.
type UnsafeClassroomServiceServer interface {
	mustEmbedUnimplementedClassroomServiceServer()
}

func RegisterClassroomServiceServer(s grpc.ServiceRegistrar, srv ClassroomServiceServer) {
	// If the following call panics, it indicates UnimplementedClassroomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClassroomService_ServiceDesc, srv)
}

func _ClassroomService_GetClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).GetClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_GetClassroom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).GetClassroom(ctx, req.(*GetClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_ListClassrooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClassroomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).ListClassrooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_ListClassrooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).ListClassrooms(ctx, req.(*ListClassroomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_CreateClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).CreateClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_CreateClassroom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).CreateClassroom(ctx, req.(*CreateClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_UpdateClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).UpdateClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_UpdateClassroom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).UpdateClassroom(ctx, req.(*UpdateClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_DeleteClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).DeleteClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_DeleteClassroom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).DeleteClassroom(ctx, req.(*DeleteClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_GetScheduleByClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleByClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).GetScheduleByClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_GetScheduleByClassroom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).GetScheduleByClassroom(ctx, req.(*GetScheduleByClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_GetScheduleByTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleByTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).GetScheduleByTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_GetScheduleByTeacher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).GetScheduleByTeacher(ctx, req.(*GetScheduleByTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_CreateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).CreateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_CreateSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).CreateSchedule(ctx, req.(*CreateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_UpdateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).UpdateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_UpdateSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).UpdateSchedule(ctx, req.(*UpdateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_DeleteSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).DeleteSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_DeleteSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).DeleteSchedule(ctx, req.(*DeleteScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClassroomService_ServiceDesc is the grpc.ServiceDesc for ClassroomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClassroomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "school_online.classroom.v1.ClassroomService",
	HandlerType: (*ClassroomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClassroom",
			Handler:    _ClassroomService_GetClassroom_Handler,
		},
		{
			MethodName: "ListClassrooms",
			Handler:    _ClassroomService_ListClassrooms_Handler,
		},
		{
			MethodName: "CreateClassroom",
			Handler:    _ClassroomService_CreateClassroom_Handler,
		},
		{
			MethodName: "UpdateClassroom",
			Handler:    _ClassroomService_UpdateClassroom_Handler,
		},
		{
			MethodName: "DeleteClassroom",
			Handler:    _ClassroomService_DeleteClassroom_Handler,
		},
		{
			MethodName: "GetScheduleByClassroom",
			Handler:    _ClassroomService_GetScheduleByClassroom_Handler,
		},
		{
			MethodName: "GetScheduleByTeacher",
			Handler:    _ClassroomService_GetScheduleByTeacher_Handler,
		},
		{
			MethodName: "CreateSchedule",
			Handler:    _ClassroomService_CreateSchedule_Handler,
		},
		{
			MethodName: "UpdateSchedule",
			Handler:    _ClassroomService_UpdateSchedule_Handler,
		},
		{
			MethodName: "DeleteSchedule",
			Handler:    _ClassroomService_DeleteSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classroom/v1/classroom.proto",
}
